export const icons = {
  car: { ios: 'car.fill', android: 'directions_car' },
  gauge: { ios: 'gauge.with.dots.needle.67percent', android: 'speed' },
  chart: { ios: 'chart.xyaxis.line', android: 'monitoring' },
  stethoscope: { ios: 'stethoscope', android: 'stethoscope' },
  settings: { ios: 'gearshape', android: 'settings' },
  bolt: { ios: 'bolt.fill', android: 'bolt' },
  antenna: { ios: 'antenna.radiowaves.left.and.right', android: 'bluetooth' },
  engine: { ios: 'engine.combustion', android: 'manufacturing' },
  record: { ios: 'record.circle', android: 'radio_button_checked' },
  stop: { ios: 'stop.fill', android: 'stop' },
  play: { ios: 'play.fill', android: 'play_arrow' },
  warning: { ios: 'exclamationmark.triangle.fill', android: 'warning' },
  checkCircle: { ios: 'checkmark.circle.fill', android: 'check_circle' },
  check: { ios: 'checkmark', android: 'check' },
  timer: { ios: 'stopwatch', android: 'timer' },
  flag: { ios: 'flag.checkered', android: 'sports_score' },
  chevronRight: { ios: 'chevron.right', android: 'chevron_right' },
  chevronDown: { ios: 'chevron.down', android: 'keyboard_arrow_down' },
  close: { ios: 'xmark', android: 'close' },
  plus: { ios: 'plus', android: 'add' },
  trash: { ios: 'trash', android: 'delete' },
  share: { ios: 'square.and.arrow.up', android: 'share' },
  info: { ios: 'info.circle', android: 'info' },
  doc: { ios: 'doc.text', android: 'description' },
  code: { ios: 'chevron.left.forwardslash.chevron.right', android: 'code' },
  battery: { ios: 'minus.plus.batteryblock', android: 'battery_charging_full' },
  thermometer: { ios: 'thermometer.medium', android: 'thermostat' },
  swap: { ios: 'arrow.triangle.2.circlepath', android: 'sync' },
  refresh: { ios: 'arrow.clockwise', android: 'refresh' },
  location: { ios: 'location.fill', android: 'location_on' },
  link: { ios: 'link', android: 'link' },
  terminal: { ios: 'terminal', android: 'terminal' },
  shield: { ios: 'checkmark.shield', android: 'verified_user' },
  wrench: { ios: 'wrench.and.screwdriver', android: 'build' },
  unlink: { ios: 'xmark.circle', android: 'link_off' },
  clock: { ios: 'clock', android: 'schedule' },
  tune: { ios: 'slider.horizontal.3', android: 'tune' },
  cart: { ios: 'cart', android: 'shopping_cart' },
  lock: { ios: 'lock.fill', android: 'lock' },
  sparkle: { ios: 'wand.and.stars', android: 'auto_fix_high' },
  speedometer: { ios: 'speedometer', android: 'speed' },
  road: { ios: 'road.lanes', android: 'road' },
  ruler: { ios: 'ruler', android: 'straighten' },
  heart: { ios: 'heart', android: 'favorite' },
  globe: { ios: 'globe', android: 'public' },
  pin: { ios: 'pin.fill', android: 'push_pin' },
  bars: { ios: 'cellularbars', android: 'signal_cellular_alt' },
  list: { ios: 'list.bullet', android: 'list' },
  grid: { ios: 'square.grid.2x2', android: 'grid_view' },
  pencil: { ios: 'pencil', android: 'edit' },
  question: { ios: 'questionmark.circle', android: 'help' },
  minusCircle: { ios: 'minus.circle', android: 'do_not_disturb_on' },
} as const;

export type IconName = keyof typeof icons;

export const filledOnAndroid: Partial<Record<IconName, boolean>> = {
  car: true,
  bolt: true,
  play: true,
  stop: true,
  warning: true,
  checkCircle: true,
  battery: true,
  location: true,
  lock: true,
  pin: true,
  record: true,
};
