import type { DtcKind } from './dtc';

const CODES: Record<string, string> = {
  P0010: '"A" Camshaft Position Actuator Circuit (Bank 1)',
  P0011: '"A" Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)',
  P0012: '"A" Camshaft Position - Timing Over-Retarded (Bank 1)',
  P0013: '"B" Camshaft Position - Actuator Circuit (Bank 1)',
  P0014: '"B" Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)',
  P0015: '"B" Camshaft Position - Timing Over-Retarded (Bank 1)',
  P0016: 'Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)',
  P0017: 'Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)',
  P0018: 'Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)',
  P0019: 'Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)',
  P0020: '"A" Camshaft Position Actuator Circuit (Bank 2)',
  P0021: '"A" Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)',
  P0022: '"A" Camshaft Position - Timing Over-Retarded (Bank 2)',
  P0023: '"B" Camshaft Position - Actuator Circuit (Bank 2)',
  P0024: '"B" Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)',
  P0025: '"B" Camshaft Position - Timing Over-Retarded (Bank 2)',
  P0026: 'Intake Valve Control Solenoid Circuit Range/Performance (Bank 1)',
  P0027: 'Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 1)',
  P0028: 'Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)',
  P0029: 'Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)',
  P0030: 'HO2S Heater Control Circuit (Bank 1 Sensor 1)',
  P0031: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 1)',
  P0032: 'HO2S Heater Control Circuit High (Bank 1 Sensor 1)',
  P0033: 'Turbocharger/Supercharger Bypass Valve Control Circuit',
  P0034: 'Turbocharger/Supercharger Bypass Valve Control Circuit Low',
  P0035: 'Turbocharger/Supercharger Bypass Valve Control Circuit High',
  P0036: 'HO2S Heater Control Circuit (Bank 1 Sensor 2)',
  P0037: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 2)',
  P0038: 'HO2S Heater Control Circuit High (Bank 1 Sensor 2)',
  P0039: 'Turbocharger/Supercharger Bypass Valve Control Circuit Range/Performance',
  P0040: 'O2 Sensor Signals Swapped Bank 1 Sensor 1 / Bank 2 Sensor 1',
  P0041: 'O2 Sensor Signals Swapped Bank 1 Sensor 2 / Bank 2 Sensor 2',
  P0042: 'HO2S Heater Control Circuit (Bank 1 Sensor 3)',
  P0043: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 3)',
  P0044: 'HO2S Heater Control Circuit High (Bank 1 Sensor 3)',
  P0045: 'Turbocharger/Supercharger Boost Control "A" Circuit/Open',
  P0046: 'Turbocharger/Supercharger Boost Control "A" Circuit Range/Performance',
  P0047: 'Turbocharger/Supercharger Boost Control "A" Circuit Low',
  P0048: 'Turbocharger/Supercharger Boost Control "A" Circuit High',
  P0049: 'Turbocharger/Supercharger Turbine Overspeed',
  P0050: 'HO2S Heater Control Circuit (Bank 2 Sensor 1)',
  P0051: 'HO2S Heater Control Circuit Low (Bank 2 Sensor 1)',
  P0052: 'HO2S Heater Control Circuit High (Bank 2 Sensor 1)',
  P0053: 'HO2S Heater Resistance (Bank 1 Sensor 1)',
  P0054: 'HO2S Heater Resistance (Bank 1 Sensor 2)',
  P0055: 'HO2S Heater Resistance (Bank 1 Sensor 3)',
  P0056: 'HO2S Heater Control Circuit (Bank 2 Sensor 2)',
  P0057: 'HO2S Heater Control Circuit Low (Bank 2 Sensor 2)',
  P0058: 'HO2S Heater Control Circuit High (Bank 2 Sensor 2)',
  P0059: 'HO2S Heater Resistance (Bank 2 Sensor 1)',
  P0060: 'HO2S Heater Resistance (Bank 2 Sensor 2)',
  P0061: 'HO2S Heater Resistance (Bank 2 Sensor 3)',
  P0062: 'HO2S Heater Control Circuit (Bank 2 Sensor 3)',
  P0063: 'HO2S Heater Control Circuit Low (Bank 2 Sensor 3)',
  P0064: 'HO2S Heater Control Circuit High (Bank 2 Sensor 3)',
  P0065: 'Air Assisted Injector Control Range/Performance',
  P0066: 'Air Assisted Injector Control Circuit or Circuit Low',
  P0067: 'Air Assisted Injector Control Circuit High',
  P0068: 'MAP/MAF - Throttle Position Correlation',
  P0069: 'Manifold Absolute Pressure - Barometric Pressure Correlation',
  P0070: 'Ambient Air Temperature Sensor Circuit',
  P0071: 'Ambient Air Temperature Sensor Range/Performance',
  P0072: 'Ambient Air Temperature Sensor Circuit Low',
  P0073: 'Ambient Air Temperature Sensor Circuit High',
  P0074: 'Ambient Air Temperature Sensor Circuit Intermittent',
  P0075: 'Intake Valve Control Solenoid Circuit (Bank 1)',
  P0076: 'Intake Valve Control Solenoid Circuit Low (Bank 1)',
  P0077: 'Intake Valve Control Solenoid Circuit High (Bank 1)',
  P0078: 'Exhaust Valve Control Solenoid Circuit (Bank 1)',
  P0079: 'Exhaust Valve Control Solenoid Circuit Low (Bank 1)',
  P0080: 'Exhaust Valve Control Solenoid Circuit High (Bank 1)',
  P0081: 'Intake Valve Control Solenoid Circuit (Bank 2)',
  P0082: 'Intake Valve Control Solenoid Circuit Low (Bank 2)',
  P0083: 'Intake Valve Control Solenoid Circuit High (Bank 2)',
  P0084: 'Exhaust Valve Control Solenoid Circuit (Bank 2)',
  P0085: 'Exhaust Valve Control Solenoid Circuit Low (Bank 2)',
  P0086: 'Exhaust Valve Control Solenoid Circuit High (Bank 2)',
  P0087: 'Fuel Rail/System Pressure - Too Low',
  P0088: 'Fuel Rail/System Pressure - Too High',
  P0089: 'Fuel Pressure Regulator 1 Performance',
  P0090: 'Fuel Pressure Regulator 1 Control Circuit',
  P0091: 'Fuel Pressure Regulator 1 Control Circuit Low',
  P0092: 'Fuel Pressure Regulator 1 Control Circuit High',
  P0093: 'Fuel System Leak Detected - Large Leak',
  P0094: 'Fuel System Leak Detected - Small Leak',
  P0095: 'Intake Air Temperature Sensor 2 Circuit',
  P0096: 'Intake Air Temperature Sensor 2 Circuit Range/Performance',
  P0097: 'Intake Air Temperature Sensor 2 Circuit Low',
  P0098: 'Intake Air Temperature Sensor 2 Circuit High',
  P0099: 'Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic',

  P0100: 'Mass or Volume Air Flow Circuit',
  P0101: 'Mass or Volume Air Flow Circuit Range/Performance',
  P0102: 'Mass or Volume Air Flow Circuit Low Input',
  P0103: 'Mass or Volume Air Flow Circuit High Input',
  P0104: 'Mass or Volume Air Flow Circuit Intermittent',
  P0105: 'Manifold Absolute Pressure/Barometric Pressure Circuit',
  P0106: 'Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance',
  P0107: 'Manifold Absolute Pressure/Barometric Pressure Circuit Low Input',
  P0108: 'Manifold Absolute Pressure/Barometric Pressure Circuit High Input',
  P0109: 'Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent',
  P0110: 'Intake Air Temperature Sensor 1 Circuit',
  P0111: 'Intake Air Temperature Sensor 1 Circuit Range/Performance',
  P0112: 'Intake Air Temperature Sensor 1 Circuit Low',
  P0113: 'Intake Air Temperature Sensor 1 Circuit High',
  P0114: 'Intake Air Temperature Sensor 1 Circuit Intermittent',
  P0115: 'Engine Coolant Temperature Circuit',
  P0116: 'Engine Coolant Temperature Circuit Range/Performance',
  P0117: 'Engine Coolant Temperature Circuit Low',
  P0118: 'Engine Coolant Temperature Circuit High',
  P0119: 'Engine Coolant Temperature Circuit Intermittent',
  P0125: 'Insufficient Coolant Temperature for Closed Loop Fuel Control',
  P0126: 'Insufficient Coolant Temperature for Stable Operation',
  P0127: 'Intake Air Temperature Too High',
  P0128: 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)',
  P0129: 'Barometric Pressure Too Low',
  P0148: 'Fuel Delivery Error',
  P0149: 'Fuel Timing Error',
  P0168: 'Fuel Temperature Too High',
  P0169: 'Incorrect Fuel Composition',
  P0170: 'Fuel Trim (Bank 1)',
  P0171: 'System Too Lean (Bank 1)',
  P0172: 'System Too Rich (Bank 1)',
  P0173: 'Fuel Trim (Bank 2)',
  P0174: 'System Too Lean (Bank 2)',
  P0175: 'System Too Rich (Bank 2)',
  P0176: 'Fuel Composition Sensor Circuit',
  P0177: 'Fuel Composition Sensor Circuit Range/Performance',
  P0178: 'Fuel Composition Sensor Circuit Low',
  P0179: 'Fuel Composition Sensor Circuit High',
  P0180: 'Fuel Temperature Sensor "A" Circuit',
  P0181: 'Fuel Temperature Sensor "A" Circuit Range/Performance',
  P0182: 'Fuel Temperature Sensor "A" Circuit Low',
  P0183: 'Fuel Temperature Sensor "A" Circuit High',
  P0184: 'Fuel Temperature Sensor "A" Circuit Intermittent',
  P0185: 'Fuel Temperature Sensor "B" Circuit',
  P0186: 'Fuel Temperature Sensor "B" Circuit Range/Performance',
  P0187: 'Fuel Temperature Sensor "B" Circuit Low',
  P0188: 'Fuel Temperature Sensor "B" Circuit High',
  P0189: 'Fuel Temperature Sensor "B" Circuit Intermittent',
  P0190: 'Fuel Rail Pressure Sensor "A" Circuit',
  P0191: 'Fuel Rail Pressure Sensor "A" Circuit Range/Performance',
  P0192: 'Fuel Rail Pressure Sensor "A" Circuit Low',
  P0193: 'Fuel Rail Pressure Sensor "A" Circuit High',
  P0194: 'Fuel Rail Pressure Sensor "A" Circuit Intermittent',
  P0195: 'Engine Oil Temperature Sensor Circuit',
  P0196: 'Engine Oil Temperature Sensor Range/Performance',
  P0197: 'Engine Oil Temperature Sensor Low',
  P0198: 'Engine Oil Temperature Sensor High',
  P0199: 'Engine Oil Temperature Sensor Intermittent',

  P0200: 'Injector Circuit/Open',
  P0213: 'Cold Start Injector 1',
  P0214: 'Cold Start Injector 2',
  P0215: 'Engine Shutoff Solenoid',
  P0216: 'Injector/Injection Timing Control Circuit',
  P0217: 'Engine Coolant Over Temperature Condition',
  P0218: 'Transmission Fluid Over Temperature Condition',
  P0219: 'Engine Overspeed Condition',
  P0230: 'Fuel Pump Primary Circuit',
  P0231: 'Fuel Pump Secondary Circuit Low',
  P0232: 'Fuel Pump Secondary Circuit High',
  P0233: 'Fuel Pump Secondary Circuit Intermittent',
  P0234: 'Turbocharger/Supercharger "A" Overboost Condition',
  P0235: 'Turbocharger/Supercharger Boost Sensor "A" Circuit',
  P0236: 'Turbocharger/Supercharger Boost Sensor "A" Circuit Range/Performance',
  P0237: 'Turbocharger/Supercharger Boost Sensor "A" Circuit Low',
  P0238: 'Turbocharger/Supercharger Boost Sensor "A" Circuit High',
  P0239: 'Turbocharger/Supercharger Boost Sensor "B" Circuit',
  P0240: 'Turbocharger/Supercharger Boost Sensor "B" Circuit Range/Performance',
  P0241: 'Turbocharger/Supercharger Boost Sensor "B" Circuit Low',
  P0242: 'Turbocharger/Supercharger Boost Sensor "B" Circuit High',
  P0243: 'Turbocharger/Supercharger Wastegate Solenoid "A"',
  P0244: 'Turbocharger/Supercharger Wastegate Solenoid "A" Range/Performance',
  P0245: 'Turbocharger/Supercharger Wastegate Solenoid "A" Low',
  P0246: 'Turbocharger/Supercharger Wastegate Solenoid "A" High',
  P0247: 'Turbocharger/Supercharger Wastegate Solenoid "B"',
  P0248: 'Turbocharger/Supercharger Wastegate Solenoid "B" Range/Performance',
  P0249: 'Turbocharger/Supercharger Wastegate Solenoid "B" Low',
  P0250: 'Turbocharger/Supercharger Wastegate Solenoid "B" High',
  P0297: 'Vehicle Overspeed Condition',
  P0298: 'Engine Oil Over Temperature',
  P0299: 'Turbocharger/Supercharger "A" Underboost Condition',

  P0300: 'Random/Multiple Cylinder Misfire Detected',
  P0313: 'Misfire Detected with Low Fuel',
  P0314: 'Single Cylinder Misfire (Cylinder not Specified)',
  P0315: 'Crankshaft Position System Variation Not Learned',
  P0316: 'Engine Misfire Detected on Startup (First 1000 Revolutions)',
  P0320: 'Ignition/Distributor Engine Speed Input Circuit',
  P0321: 'Ignition/Distributor Engine Speed Input Circuit Range/Performance',
  P0322: 'Ignition/Distributor Engine Speed Input Circuit No Signal',
  P0323: 'Ignition/Distributor Engine Speed Input Circuit Intermittent',
  P0324: 'Knock Control System Error',
  P0325: 'Knock Sensor 1 Circuit (Bank 1 or Single Sensor)',
  P0326: 'Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)',
  P0327: 'Knock Sensor 1 Circuit Low (Bank 1 or Single Sensor)',
  P0328: 'Knock Sensor 1 Circuit High (Bank 1 or Single Sensor)',
  P0329: 'Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)',
  P0330: 'Knock Sensor 2 Circuit (Bank 2)',
  P0331: 'Knock Sensor 2 Circuit Range/Performance (Bank 2)',
  P0332: 'Knock Sensor 2 Circuit Low (Bank 2)',
  P0333: 'Knock Sensor 2 Circuit High (Bank 2)',
  P0334: 'Knock Sensor 2 Circuit Intermittent (Bank 2)',
  P0335: 'Crankshaft Position Sensor "A" Circuit',
  P0336: 'Crankshaft Position Sensor "A" Circuit Range/Performance',
  P0337: 'Crankshaft Position Sensor "A" Circuit Low',
  P0338: 'Crankshaft Position Sensor "A" Circuit High',
  P0339: 'Crankshaft Position Sensor "A" Circuit Intermittent',
  P0340: 'Camshaft Position Sensor "A" Circuit (Bank 1 or Single Sensor)',
  P0341: 'Camshaft Position Sensor "A" Circuit Range/Performance (Bank 1 or Single Sensor)',
  P0342: 'Camshaft Position Sensor "A" Circuit Low (Bank 1 or Single Sensor)',
  P0343: 'Camshaft Position Sensor "A" Circuit High (Bank 1 or Single Sensor)',
  P0344: 'Camshaft Position Sensor "A" Circuit Intermittent (Bank 1 or Single Sensor)',
  P0345: 'Camshaft Position Sensor "A" Circuit (Bank 2)',
  P0346: 'Camshaft Position Sensor "A" Circuit Range/Performance (Bank 2)',
  P0347: 'Camshaft Position Sensor "A" Circuit Low (Bank 2)',
  P0348: 'Camshaft Position Sensor "A" Circuit High (Bank 2)',
  P0349: 'Camshaft Position Sensor "A" Circuit Intermittent (Bank 2)',
  P0350: 'Ignition Coil Primary/Secondary Circuit',
  P0365: 'Camshaft Position Sensor "B" Circuit (Bank 1)',
  P0366: 'Camshaft Position Sensor "B" Circuit Range/Performance (Bank 1)',
  P0367: 'Camshaft Position Sensor "B" Circuit Low (Bank 1)',
  P0368: 'Camshaft Position Sensor "B" Circuit High (Bank 1)',
  P0369: 'Camshaft Position Sensor "B" Circuit Intermittent (Bank 1)',
  P0390: 'Camshaft Position Sensor "B" Circuit (Bank 2)',
  P0391: 'Camshaft Position Sensor "B" Circuit Range/Performance (Bank 2)',
  P0392: 'Camshaft Position Sensor "B" Circuit Low (Bank 2)',
  P0393: 'Camshaft Position Sensor "B" Circuit High (Bank 2)',
  P0394: 'Camshaft Position Sensor "B" Circuit Intermittent (Bank 2)',

  P0400: 'Exhaust Gas Recirculation "A" Flow',
  P0401: 'Exhaust Gas Recirculation "A" Flow Insufficient Detected',
  P0402: 'Exhaust Gas Recirculation "A" Flow Excessive Detected',
  P0403: 'Exhaust Gas Recirculation "A" Control Circuit',
  P0404: 'Exhaust Gas Recirculation "A" Control Circuit Range/Performance',
  P0405: 'Exhaust Gas Recirculation Sensor "A" Circuit Low',
  P0406: 'Exhaust Gas Recirculation Sensor "A" Circuit High',
  P0407: 'Exhaust Gas Recirculation Sensor "B" Circuit Low',
  P0408: 'Exhaust Gas Recirculation Sensor "B" Circuit High',
  P0409: 'Exhaust Gas Recirculation Sensor "A" Circuit',
  P0410: 'Secondary Air Injection System',
  P0411: 'Secondary Air Injection System Incorrect Flow Detected',
  P0412: 'Secondary Air Injection System Switching Valve "A" Circuit',
  P0413: 'Secondary Air Injection System Switching Valve "A" Circuit Open',
  P0414: 'Secondary Air Injection System Switching Valve "A" Circuit Shorted',
  P0415: 'Secondary Air Injection System Switching Valve "B" Circuit',
  P0416: 'Secondary Air Injection System Switching Valve "B" Circuit Open',
  P0417: 'Secondary Air Injection System Switching Valve "B" Circuit Shorted',
  P0418: 'Secondary Air Injection System Control "A" Circuit',
  P0419: 'Secondary Air Injection System Control "B" Circuit',
  P0420: 'Catalyst System Efficiency Below Threshold (Bank 1)',
  P0421: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
  P0422: 'Main Catalyst Efficiency Below Threshold (Bank 1)',
  P0423: 'Heated Catalyst Efficiency Below Threshold (Bank 1)',
  P0424: 'Heated Catalyst Temperature Below Threshold (Bank 1)',
  P0430: 'Catalyst System Efficiency Below Threshold (Bank 2)',
  P0431: 'Warm Up Catalyst Efficiency Below Threshold (Bank 2)',
  P0432: 'Main Catalyst Efficiency Below Threshold (Bank 2)',
  P0433: 'Heated Catalyst Efficiency Below Threshold (Bank 2)',
  P0434: 'Heated Catalyst Temperature Below Threshold (Bank 2)',
  P0440: 'Evaporative Emission System',
  P0441: 'Evaporative Emission System Incorrect Purge Flow',
  P0442: 'Evaporative Emission System Leak Detected (Small Leak)',
  P0443: 'Evaporative Emission System Purge Control Valve "A" Circuit',
  P0444: 'Evaporative Emission System Purge Control Valve "A" Circuit Open',
  P0445: 'Evaporative Emission System Purge Control Valve "A" Circuit Shorted',
  P0446: 'Evaporative Emission System Vent Control Circuit',
  P0447: 'Evaporative Emission System Vent Control Circuit Open',
  P0448: 'Evaporative Emission System Vent Control Circuit Shorted',
  P0449: 'Evaporative Emission System Vent Valve/Solenoid Circuit',
  P0450: 'Evaporative Emission System Pressure Sensor/Switch',
  P0451: 'Evaporative Emission System Pressure Sensor/Switch Range/Performance',
  P0452: 'Evaporative Emission System Pressure Sensor/Switch Low',
  P0453: 'Evaporative Emission System Pressure Sensor/Switch High',
  P0454: 'Evaporative Emission System Pressure Sensor/Switch Intermittent',
  P0455: 'Evaporative Emission System Leak Detected (Large Leak)',
  P0456: 'Evaporative Emission System Leak Detected (Very Small Leak)',
  P0457: 'Evaporative Emission System Leak Detected (Fuel Cap Loose/Off)',
  P0458: 'Evaporative Emission System Purge Control Valve "A" Circuit Low',
  P0459: 'Evaporative Emission System Purge Control Valve "A" Circuit High',
  P0460: 'Fuel Level Sensor "A" Circuit',
  P0461: 'Fuel Level Sensor "A" Circuit Range/Performance',
  P0462: 'Fuel Level Sensor "A" Circuit Low',
  P0463: 'Fuel Level Sensor "A" Circuit High',
  P0464: 'Fuel Level Sensor "A" Circuit Intermittent',
  P0465: 'EVAP Purge Flow Sensor Circuit',
  P0466: 'EVAP Purge Flow Sensor Circuit Range/Performance',
  P0467: 'EVAP Purge Flow Sensor Circuit Low',
  P0468: 'EVAP Purge Flow Sensor Circuit High',
  P0469: 'EVAP Purge Flow Sensor Circuit Intermittent',
  P0470: 'Exhaust Pressure Sensor "A" Circuit',
  P0471: 'Exhaust Pressure Sensor "A" Circuit Range/Performance',
  P0472: 'Exhaust Pressure Sensor "A" Circuit Low',
  P0473: 'Exhaust Pressure Sensor "A" Circuit High',
  P0474: 'Exhaust Pressure Sensor "A" Circuit Intermittent',
  P0480: 'Fan 1 Control Circuit',
  P0481: 'Fan 2 Control Circuit',
  P0482: 'Fan 3 Control Circuit',
  P0483: 'Fan Rationality Check',
  P0484: 'Fan Circuit Over Current',
  P0485: 'Fan Power/Ground Circuit',
  P0491: 'Secondary Air Injection System Insufficient Flow (Bank 1)',
  P0492: 'Secondary Air Injection System Insufficient Flow (Bank 2)',
  P0496: 'Evaporative Emission System High Purge Flow',
  P0497: 'Evaporative Emission System Low Purge Flow',
  P0498: 'Evaporative Emission System Vent Valve Control Circuit Low',
  P0499: 'Evaporative Emission System Vent Valve Control Circuit High',

  P0500: 'Vehicle Speed Sensor "A"',
  P0501: 'Vehicle Speed Sensor "A" Range/Performance',
  P0502: 'Vehicle Speed Sensor "A" Circuit Low Input',
  P0503: 'Vehicle Speed Sensor "A" Intermittent/Erratic/High',
  P0504: 'Brake Switch "A"/"B" Correlation',
  P0505: 'Idle Air Control System',
  P0506: 'Idle Air Control System RPM Lower Than Expected',
  P0507: 'Idle Air Control System RPM Higher Than Expected',
  P0508: 'Idle Air Control System Circuit Low',
  P0509: 'Idle Air Control System Circuit High',
  P0510: 'Closed Throttle Position Switch',
  P0511: 'Idle Air Control Circuit',
  P0512: 'Starter Request Circuit',
  P0513: 'Invalid Immobilizer Key',
  P0515: 'Battery Temperature Sensor Circuit',
  P0516: 'Battery Temperature Sensor Circuit Low',
  P0517: 'Battery Temperature Sensor Circuit High',
  P0520: 'Engine Oil Pressure Sensor/Switch Circuit',
  P0521: 'Engine Oil Pressure Sensor/Switch Range/Performance',
  P0522: 'Engine Oil Pressure Sensor/Switch Low Voltage',
  P0523: 'Engine Oil Pressure Sensor/Switch High Voltage',
  P0524: 'Engine Oil Pressure Too Low',
  P0530: 'A/C Refrigerant Pressure Sensor "A" Circuit',
  P0531: 'A/C Refrigerant Pressure Sensor "A" Circuit Range/Performance',
  P0532: 'A/C Refrigerant Pressure Sensor "A" Circuit Low',
  P0533: 'A/C Refrigerant Pressure Sensor "A" Circuit High',
  P0534: 'Air Conditioner Refrigerant Charge Loss',
  P0550: 'Power Steering Pressure Sensor/Switch Circuit',
  P0551: 'Power Steering Pressure Sensor/Switch Circuit Range/Performance',
  P0552: 'Power Steering Pressure Sensor/Switch Circuit Low Input',
  P0553: 'Power Steering Pressure Sensor/Switch Circuit High Input',
  P0554: 'Power Steering Pressure Sensor/Switch Circuit Intermittent',
  P0560: 'System Voltage',
  P0561: 'System Voltage Unstable',
  P0562: 'System Voltage Low',
  P0563: 'System Voltage High',
  P0564: 'Cruise Control Multi-Function Input "A" Circuit',
  P0565: 'Cruise Control On Signal',
  P0566: 'Cruise Control Off Signal',
  P0567: 'Cruise Control Resume Signal',
  P0568: 'Cruise Control Set Signal',
  P0569: 'Cruise Control Coast Signal',
  P0570: 'Cruise Control Accelerate Signal',
  P0571: 'Brake Switch "A" Circuit',
  P0572: 'Brake Switch "A" Circuit Low',
  P0573: 'Brake Switch "A" Circuit High',
  P0574: 'Cruise Control System - Vehicle Speed Too High',
  P0575: 'Cruise Control Input Circuit',

  P0600: 'Serial Communication Link',
  P0601: 'Internal Control Module Memory Check Sum Error',
  P0602: 'Control Module Programming Error',
  P0603: 'Internal Control Module Keep Alive Memory (KAM) Error',
  P0604: 'Internal Control Module Random Access Memory (RAM) Error',
  P0605: 'Internal Control Module Read Only Memory (ROM) Error',
  P0606: 'Control Module Processor',
  P0607: 'Control Module Performance',
  P0608: 'Control Module VSS Output "A"',
  P0609: 'Control Module VSS Output "B"',
  P0610: 'Control Module Vehicle Options Error',
  P0611: 'Fuel Injector Control Module Performance',
  P0612: 'Fuel Injector Control Module Relay Control',
  P0613: 'TCM Processor',
  P0614: 'ECM / TCM Incompatible',
  P0615: 'Starter Relay Circuit',
  P0616: 'Starter Relay Circuit Low',
  P0617: 'Starter Relay Circuit High',
  P0620: 'Generator Control Circuit',
  P0621: 'Generator Lamp/L Terminal Control Circuit',
  P0622: 'Generator Field/F Terminal Control Circuit',
  P0623: 'Generator Lamp Control Circuit',
  P0624: 'Fuel Cap Lamp Control Circuit',
  P0625: 'Generator Field/F Terminal Circuit Low',
  P0626: 'Generator Field/F Terminal Circuit High',
  P0627: 'Fuel Pump "A" Control Circuit/Open',
  P0628: 'Fuel Pump "A" Control Circuit Low',
  P0629: 'Fuel Pump "A" Control Circuit High',
  P0630: 'VIN Not Programmed or Incompatible - ECM/PCM',
  P0631: 'VIN Not Programmed or Incompatible - TCM',
  P0632: 'Odometer Not Programmed - ECM/PCM',
  P0633: 'Immobilizer Key Not Programmed - ECM/PCM',
  P0634: 'PCM/ECM/TCM Internal Temperature Too High',
  P0638: 'Throttle Actuator Control Range/Performance (Bank 1)',
  P0639: 'Throttle Actuator Control Range/Performance (Bank 2)',
  P0640: 'Intake Air Heater Control Circuit',
  P0641: 'Sensor Reference Voltage "A" Circuit/Open',
  P0642: 'Sensor Reference Voltage "A" Circuit Low',
  P0643: 'Sensor Reference Voltage "A" Circuit High',
  P0644: 'Driver Display Serial Communication Circuit',
  P0645: 'A/C Clutch Relay Control Circuit',
  P0646: 'A/C Clutch Relay Control Circuit Low',
  P0647: 'A/C Clutch Relay Control Circuit High',
  P0648: 'Immobilizer Lamp Control Circuit',
  P0649: 'Speed Control Lamp Control Circuit',
  P0650: 'Malfunction Indicator Lamp (MIL) Control Circuit',
  P0651: 'Sensor Reference Voltage "B" Circuit/Open',
  P0652: 'Sensor Reference Voltage "B" Circuit Low',
  P0653: 'Sensor Reference Voltage "B" Circuit High',
  P0654: 'Engine RPM Output Circuit',
  P0655: 'Engine Hot Lamp Output Control Circuit',
  P0656: 'Fuel Level Output Circuit',
  P0657: 'Actuator Supply Voltage "A" Circuit/Open',
  P0658: 'Actuator Supply Voltage "A" Circuit Low',
  P0659: 'Actuator Supply Voltage "A" Circuit High',
  P0660: 'Intake Manifold Tuning Valve Control Circuit/Open (Bank 1)',
  P0661: 'Intake Manifold Tuning Valve Control Circuit Low (Bank 1)',
  P0662: 'Intake Manifold Tuning Valve Control Circuit High (Bank 1)',
  P0663: 'Intake Manifold Tuning Valve Control Circuit/Open (Bank 2)',
  P0664: 'Intake Manifold Tuning Valve Control Circuit Low (Bank 2)',
  P0665: 'Intake Manifold Tuning Valve Control Circuit High (Bank 2)',
  P0666: 'PCM/ECM/TCM Internal Temperature Sensor Circuit',
  P0667: 'PCM/ECM/TCM Internal Temperature Sensor Range/Performance',
  P0668: 'PCM/ECM/TCM Internal Temperature Sensor Circuit Low',
  P0669: 'PCM/ECM/TCM Internal Temperature Sensor Circuit High',
  P0685: 'ECM/PCM Power Relay Control Circuit/Open',
  P0686: 'ECM/PCM Power Relay Control Circuit Low',
  P0687: 'ECM/PCM Power Relay Control Circuit High',
  P0688: 'ECM/PCM Power Relay Sense Circuit/Open',
  P0689: 'ECM/PCM Power Relay Sense Circuit Low',
  P0690: 'ECM/PCM Power Relay Sense Circuit High',
  P0691: 'Fan 1 Control Circuit Low',
  P0692: 'Fan 1 Control Circuit High',
  P0693: 'Fan 2 Control Circuit Low',
  P0694: 'Fan 2 Control Circuit High',
  P0695: 'Fan 3 Control Circuit Low',
  P0696: 'Fan 3 Control Circuit High',
  P0697: 'Sensor Reference Voltage "C" Circuit/Open',
  P0698: 'Sensor Reference Voltage "C" Circuit Low',
  P0699: 'Sensor Reference Voltage "C" Circuit High',

  P0700: 'Transmission Control System (MIL Request)',
  P0701: 'Transmission Control System Range/Performance',
  P0702: 'Transmission Control System Electrical',
  P0705: 'Transmission Range Sensor "A" Circuit (PRNDL Input)',
  P0706: 'Transmission Range Sensor "A" Circuit Range/Performance',
  P0710: 'Transmission Fluid Temperature Sensor "A" Circuit',
  P0711: 'Transmission Fluid Temperature Sensor "A" Circuit Range/Performance',
  P0712: 'Transmission Fluid Temperature Sensor "A" Circuit Low',
  P0713: 'Transmission Fluid Temperature Sensor "A" Circuit High',
  P0715: 'Input/Turbine Speed Sensor "A" Circuit',
  P0716: 'Input/Turbine Speed Sensor "A" Circuit Range/Performance',
  P0717: 'Input/Turbine Speed Sensor "A" Circuit No Signal',
  P0720: 'Output Shaft Speed Sensor Circuit',
  P0721: 'Output Shaft Speed Sensor Circuit Range/Performance',
  P0722: 'Output Shaft Speed Sensor Circuit No Signal',
  P0730: 'Incorrect Gear Ratio',
  P0731: 'Gear 1 Incorrect Ratio',
  P0732: 'Gear 2 Incorrect Ratio',
  P0733: 'Gear 3 Incorrect Ratio',
  P0734: 'Gear 4 Incorrect Ratio',
  P0735: 'Gear 5 Incorrect Ratio',
  P0736: 'Reverse Incorrect Ratio',
  P0740: 'Torque Converter Clutch Solenoid Circuit/Open',
  P0741: 'Torque Converter Clutch Solenoid Circuit Performance/Stuck Off',

  P2004: 'Intake Manifold Runner Control Stuck Open (Bank 1)',
  P2005: 'Intake Manifold Runner Control Stuck Open (Bank 2)',
  P2006: 'Intake Manifold Runner Control Stuck Closed (Bank 1)',
  P2007: 'Intake Manifold Runner Control Stuck Closed (Bank 2)',
  P2008: 'Intake Manifold Runner Control Circuit/Open (Bank 1)',
  P2009: 'Intake Manifold Runner Control Circuit Low (Bank 1)',
  P2010: 'Intake Manifold Runner Control Circuit High (Bank 1)',
  P2011: 'Intake Manifold Runner Control Circuit/Open (Bank 2)',
  P2012: 'Intake Manifold Runner Control Circuit Low (Bank 2)',
  P2013: 'Intake Manifold Runner Control Circuit High (Bank 2)',
  P2014: 'Intake Manifold Runner Position Sensor/Switch Circuit (Bank 1)',
  P2015: 'Intake Manifold Runner Position Sensor/Switch Circuit Range/Performance (Bank 1)',
  P2016: 'Intake Manifold Runner Position Sensor/Switch Circuit Low (Bank 1)',
  P2017: 'Intake Manifold Runner Position Sensor/Switch Circuit High (Bank 1)',
  P2018: 'Intake Manifold Runner Position Sensor/Switch Circuit Intermittent (Bank 1)',
  P2019: 'Intake Manifold Runner Position Sensor/Switch Circuit (Bank 2)',
  P2020: 'Intake Manifold Runner Position Sensor/Switch Circuit Range/Performance (Bank 2)',
  P2021: 'Intake Manifold Runner Position Sensor/Switch Circuit Low (Bank 2)',
  P2022: 'Intake Manifold Runner Position Sensor/Switch Circuit High (Bank 2)',
  P2023: 'Intake Manifold Runner Position Sensor/Switch Circuit Intermittent (Bank 2)',
  P2088: '"A" Camshaft Position Actuator Control Circuit Low (Bank 1)',
  P2089: '"A" Camshaft Position Actuator Control Circuit High (Bank 1)',
  P2090: '"B" Camshaft Position Actuator Control Circuit Low (Bank 1)',
  P2091: '"B" Camshaft Position Actuator Control Circuit High (Bank 1)',
  P2092: '"A" Camshaft Position Actuator Control Circuit Low (Bank 2)',
  P2093: '"A" Camshaft Position Actuator Control Circuit High (Bank 2)',
  P2094: '"B" Camshaft Position Actuator Control Circuit Low (Bank 2)',
  P2095: '"B" Camshaft Position Actuator Control Circuit High (Bank 2)',
  P2096: 'Post Catalyst Fuel Trim System Too Lean (Bank 1)',
  P2097: 'Post Catalyst Fuel Trim System Too Rich (Bank 1)',
  P2098: 'Post Catalyst Fuel Trim System Too Lean (Bank 2)',
  P2099: 'Post Catalyst Fuel Trim System Too Rich (Bank 2)',
  P2100: 'Throttle Actuator "A" Control Motor Circuit/Open',
  P2101: 'Throttle Actuator "A" Control Motor Circuit Range/Performance',
  P2102: 'Throttle Actuator "A" Control Motor Circuit Low',
  P2103: 'Throttle Actuator "A" Control Motor Circuit High',
  P2104: 'Throttle Actuator Control System - Forced Idle',
  P2105: 'Throttle Actuator Control System - Forced Engine Shutdown',
  P2106: 'Throttle Actuator Control System - Forced Limited Power',
  P2107: 'Throttle Actuator Control Module Processor',
  P2108: 'Throttle Actuator Control Module Performance',
  P2109: 'Throttle/Pedal Position Sensor "A" Minimum Stop Performance',
  P2110: 'Throttle Actuator Control System - Forced Limited RPM',
  P2111: 'Throttle Actuator Control System - Stuck Open',
  P2112: 'Throttle Actuator Control System - Stuck Closed',
  P2113: 'Throttle/Pedal Position Sensor "B" Minimum Stop Performance',
  P2114: 'Throttle/Pedal Position Sensor "C" Minimum Stop Performance',
  P2115: 'Throttle/Pedal Position Sensor "D" Minimum Stop Performance',
  P2116: 'Throttle/Pedal Position Sensor "E" Minimum Stop Performance',
  P2117: 'Throttle/Pedal Position Sensor "F" Minimum Stop Performance',
  P2118: 'Throttle Actuator "A" Control Motor Current Range/Performance',
  P2119: 'Throttle Actuator "A" Control Throttle Body Range/Performance',
  P2135: 'Throttle/Pedal Position Sensor/Switch "A"/"B" Voltage Correlation',
  P2136: 'Throttle/Pedal Position Sensor/Switch "A"/"C" Voltage Correlation',
  P2137: 'Throttle/Pedal Position Sensor/Switch "B"/"C" Voltage Correlation',
  P2138: 'Throttle/Pedal Position Sensor/Switch "D"/"E" Voltage Correlation',
  P2139: 'Throttle/Pedal Position Sensor/Switch "D"/"F" Voltage Correlation',
  P2140: 'Throttle/Pedal Position Sensor/Switch "E"/"F" Voltage Correlation',
  P2158: 'Vehicle Speed Sensor "B"',
  P2159: 'Vehicle Speed Sensor "B" Range/Performance',
  P2160: 'Vehicle Speed Sensor "B" Circuit Low',
  P2161: 'Vehicle Speed Sensor "B" Intermittent/Erratic',
  P2176: 'Throttle Actuator Control System - Idle Position Not Learned',
  P2177: 'System Too Lean Off Idle (Bank 1)',
  P2178: 'System Too Rich Off Idle (Bank 1)',
  P2179: 'System Too Lean Off Idle (Bank 2)',
  P2180: 'System Too Rich Off Idle (Bank 2)',
  P2181: 'Cooling System Performance',
  P2182: 'Engine Coolant Temperature Sensor 2 Circuit',
  P2183: 'Engine Coolant Temperature Sensor 2 Circuit Range/Performance',
  P2184: 'Engine Coolant Temperature Sensor 2 Circuit Low',
  P2185: 'Engine Coolant Temperature Sensor 2 Circuit High',
  P2186: 'Engine Coolant Temperature Sensor 2 Circuit Intermittent/Erratic',
  P2187: 'System Too Lean at Idle (Bank 1)',
  P2188: 'System Too Rich at Idle (Bank 1)',
  P2189: 'System Too Lean at Idle (Bank 2)',
  P2190: 'System Too Rich at Idle (Bank 2)',
  P2191: 'System Too Lean at Higher Load (Bank 1)',
  P2192: 'System Too Rich at Higher Load (Bank 1)',
  P2193: 'System Too Lean at Higher Load (Bank 2)',
  P2194: 'System Too Rich at Higher Load (Bank 2)',
  P2195: 'O2 Sensor Signal Biased/Stuck Lean (Bank 1 Sensor 1)',
  P2196: 'O2 Sensor Signal Biased/Stuck Rich (Bank 1 Sensor 1)',
  P2197: 'O2 Sensor Signal Biased/Stuck Lean (Bank 2 Sensor 1)',
  P2198: 'O2 Sensor Signal Biased/Stuck Rich (Bank 2 Sensor 1)',
  P2199: 'Intake Air Temperature Sensor 1/2 Correlation',
  P2226: 'Barometric Pressure Circuit',
  P2227: 'Barometric Pressure Circuit Range/Performance',
  P2228: 'Barometric Pressure Circuit Low',
  P2229: 'Barometric Pressure Circuit High',
  P2230: 'Barometric Pressure Circuit Intermittent',
  P2237: 'O2 Sensor Positive Current Control Circuit/Open (Bank 1 Sensor 1)',
  P2238: 'O2 Sensor Positive Current Control Circuit Low (Bank 1 Sensor 1)',
  P2239: 'O2 Sensor Positive Current Control Circuit High (Bank 1 Sensor 1)',
  P2240: 'O2 Sensor Positive Current Control Circuit/Open (Bank 2 Sensor 1)',
  P2241: 'O2 Sensor Positive Current Control Circuit Low (Bank 2 Sensor 1)',
  P2242: 'O2 Sensor Positive Current Control Circuit High (Bank 2 Sensor 1)',
  P2243: 'O2 Sensor Reference Voltage Circuit/Open (Bank 1 Sensor 1)',
  P2244: 'O2 Sensor Reference Voltage Performance (Bank 1 Sensor 1)',
  P2245: 'O2 Sensor Reference Voltage Circuit Low (Bank 1 Sensor 1)',
  P2246: 'O2 Sensor Reference Voltage Circuit High (Bank 1 Sensor 1)',
  P2247: 'O2 Sensor Reference Voltage Circuit/Open (Bank 2 Sensor 1)',
  P2248: 'O2 Sensor Reference Voltage Performance (Bank 2 Sensor 1)',
  P2249: 'O2 Sensor Reference Voltage Circuit Low (Bank 2 Sensor 1)',
  P2250: 'O2 Sensor Reference Voltage Circuit High (Bank 2 Sensor 1)',
  P2251: 'O2 Sensor Negative Current Control Circuit/Open (Bank 1 Sensor 1)',
  P2252: 'O2 Sensor Negative Current Control Circuit Low (Bank 1 Sensor 1)',
  P2253: 'O2 Sensor Negative Current Control Circuit High (Bank 1 Sensor 1)',
  P2254: 'O2 Sensor Negative Current Control Circuit/Open (Bank 2 Sensor 1)',
  P2255: 'O2 Sensor Negative Current Control Circuit Low (Bank 2 Sensor 1)',
  P2256: 'O2 Sensor Negative Current Control Circuit High (Bank 2 Sensor 1)',
  P2257: 'Secondary Air Injection System Control "A" Circuit Low',
  P2258: 'Secondary Air Injection System Control "A" Circuit High',
  P2259: 'Secondary Air Injection System Control "B" Circuit Low',
  P2260: 'Secondary Air Injection System Control "B" Circuit High',
  P2261: 'Turbocharger/Supercharger Bypass Valve - Mechanical',
  P2262: 'Turbocharger/Supercharger Boost Pressure Not Detected - Mechanical',
  P2263: 'Turbocharger/Supercharger Boost System Performance',
  P2270: 'O2 Sensor Signal Biased/Stuck Lean (Bank 1 Sensor 2)',
  P2271: 'O2 Sensor Signal Biased/Stuck Rich (Bank 1 Sensor 2)',
  P2272: 'O2 Sensor Signal Biased/Stuck Lean (Bank 2 Sensor 2)',
  P2273: 'O2 Sensor Signal Biased/Stuck Rich (Bank 2 Sensor 2)',
  P2274: 'O2 Sensor Signal Biased/Stuck Lean (Bank 1 Sensor 3)',
  P2275: 'O2 Sensor Signal Biased/Stuck Rich (Bank 1 Sensor 3)',
  P2276: 'O2 Sensor Signal Biased/Stuck Lean (Bank 2 Sensor 3)',
  P2277: 'O2 Sensor Signal Biased/Stuck Rich (Bank 2 Sensor 3)',
  P2278: 'O2 Sensor Signals Swapped Bank 1 Sensor 3 / Bank 2 Sensor 3',
  P2279: 'Intake Air System Leak',
  P2280: 'Air Flow Restriction / Air Leak Between Air Filter and MAF',
  P2281: 'Air Leak Between MAF and Throttle Body',
  P2282: 'Air Leak Between Throttle Body and Intake Valves',
  P2293: 'Fuel Pressure Regulator 2 Performance',
  P2294: 'Fuel Pressure Regulator 2 Control Circuit',
  P2295: 'Fuel Pressure Regulator 2 Control Circuit Low',
  P2296: 'Fuel Pressure Regulator 2 Control Circuit High',

  U0001: 'High Speed CAN Communication Bus',
  U0002: 'High Speed CAN Communication Bus (Performance)',
  U0003: 'High Speed CAN Communication Bus (+) Open',
  U0004: 'High Speed CAN Communication Bus (+) Low',
  U0005: 'High Speed CAN Communication Bus (+) High',
  U0006: 'High Speed CAN Communication Bus (-) Open',
  U0007: 'High Speed CAN Communication Bus (-) Low',
  U0008: 'High Speed CAN Communication Bus (-) High',
  U0009: 'High Speed CAN Communication Bus (-) Shorted to Bus (+)',
  U0073: 'Control Module Communication Bus "A" Off',
  U0074: 'Control Module Communication Bus "B" Off',
  U0100: 'Lost Communication With ECM/PCM "A"',
  U0101: 'Lost Communication With TCM',
  U0102: 'Lost Communication With Transfer Case Control Module',
  U0107: 'Lost Communication With Throttle Actuator Control Module',
  U0121: 'Lost Communication With Anti-Lock Brake System (ABS) Control Module',
  U0122: 'Lost Communication With Vehicle Dynamics Control Module',
  U0126: 'Lost Communication With Steering Angle Sensor Module',
  U0140: 'Lost Communication With Body Control Module',
  U0151: 'Lost Communication With Restraints Control Module',
  U0155: 'Lost Communication With Instrument Panel Cluster (IPC) Control Module',
  U0164: 'Lost Communication With HVAC Control Module',
  U0167: 'Lost Communication With Vehicle Immobilizer Control Module',
  U0300: 'Internal Control Module Software Incompatibility',
  U0401: 'Invalid Data Received From ECM/PCM "A"',
  U0415: 'Invalid Data Received From Anti-Lock Brake System (ABS) Control Module',
};

const LETTERS = 'ABCDEFGHIJKL';

const p = (n: number) => `P${n.toString().padStart(4, '0')}`;

const O2_SENSORS: [number, string][] = [
  [130, 'Bank 1 Sensor 1'],
  [136, 'Bank 1 Sensor 2'],
  [142, 'Bank 1 Sensor 3'],
  [150, 'Bank 2 Sensor 1'],
  [156, 'Bank 2 Sensor 2'],
  [162, 'Bank 2 Sensor 3'],
];

const O2_FAULTS = [
  'O2 Sensor Circuit',
  'O2 Sensor Circuit Low Voltage',
  'O2 Sensor Circuit High Voltage',
  'O2 Sensor Circuit Slow Response',
  'O2 Sensor Circuit No Activity Detected',
  'O2 Sensor Heater Circuit',
];

const PEDAL_SENSORS: [number, string][] = [
  [120, 'A'],
  [220, 'B'],
  [225, 'C'],
  [2120, 'D'],
  [2125, 'E'],
  [2130, 'F'],
];

const PEDAL_FAULTS = ['Circuit', 'Circuit Range/Performance', 'Circuit Low', 'Circuit High', 'Circuit Intermittent'];

O2_SENSORS.forEach(([base, location], index) => {
  O2_FAULTS.forEach((fault, i) => {
    CODES[p(base + i)] = `${fault} (${location})`;
  });
  CODES[p(2231 + index)] = `O2 Sensor Signal Circuit Shorted to Heater Circuit (${location})`;
});

for (const [base, sensor] of PEDAL_SENSORS) {
  PEDAL_FAULTS.forEach((fault, i) => {
    CODES[p(base + i)] = `Throttle/Pedal Position Sensor/Switch "${sensor}" ${fault}`;
  });
}

for (let cylinder = 1; cylinder <= 12; cylinder++) {
  CODES[p(200 + cylinder)] = `Injector Circuit/Open - Cylinder ${cylinder}`;
  CODES[p(300 + cylinder)] = `Cylinder ${cylinder} Misfire Detected`;
  CODES[p(350 + cylinder)] = `Ignition Coil "${LETTERS[cylinder - 1]}" Primary/Secondary Circuit`;
  const injector = 261 + (cylinder - 1) * 3;
  CODES[p(injector)] = `Cylinder ${cylinder} Injector Circuit Low`;
  CODES[p(injector + 1)] = `Cylinder ${cylinder} Injector Circuit High`;
  CODES[p(injector + 2)] = `Cylinder ${cylinder} Contribution/Balance`;
}

export function describeDtc(code: string): string | undefined {
  return CODES[code.trim().toUpperCase()];
}

export const DTC_KIND_INFO: Record<DtcKind, { label: string; detail: string }> = {
  stored: { label: 'Stored', detail: 'Confirmed fault. It can turn on the check engine lamp.' },
  pending: { label: 'Pending', detail: 'Detected during the current or last drive cycle but not confirmed yet.' },
  permanent: { label: 'Permanent', detail: 'Only the engine computer can erase it, after it has verified the repair.' },
};

export const DTC_KINDS: DtcKind[] = ['stored', 'pending', 'permanent'];

export function isDtcKind(value: unknown): value is DtcKind {
  return DTC_KINDS.some((kind) => kind === value);
}
